import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";
import store from "@/redux/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navLinks = [
    { label: "Login", href: "/signin" },
    { label: "Table", href: "/table" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Navigation navLinks={navLinks} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
